services:
  verba:
    build:
      context: ./
      dockerfile: /Dockerfile
    ports:
      - 8000:8000
    environment:
      - OLLAMA_URL=http://10.1.1.237:11434
      - OLLAMA_MODEL=llama3.2:3b
      - OLLAMA_EMBED_MODEL=nomic-embed-text

    volumes:
      - ./data:/data/
    depends_on:
      weaviate:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - ollama-docker

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:latest
    ports:
      - 8080:8080
      - 3000:8080
      - 50051:50051
      # - 8079:8079
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'e'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - ollama-docker

volumes:
  weaviate_data: {}


networks:
  ollama-docker:
    external: false